[package]
name = "admin-pass"
version = "0.1.0"
authors = ["Wojciech Szęszoł <keepitsimplesirius@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
base64 = "^0.12"
hex = "^0.4.2"
rand = "^0.7"
sha2 = "^0.9.0"