use std;
use serde::{de};

pub type Result<T> = std::result::Result<T, Error>;

#[derive(Clone, Debug, PartialEq)]
pub struct Error {
    pub sql_state : SqlState,
    pub details : String
}

impl Error {
    pub fn from_sql_state(sql_state : SqlState) -> Self {
        Error { sql_state : sql_state, details : String::new() }
    }
}

impl de::Error for Error {
    fn custom<T: std::fmt::Display>(msg: T) -> Self {
        Error { sql_state : SqlState::DeserializeError, details : msg.to_string() }
    }
}

impl std::fmt::Display for Error {
    fn fmt(&self, formatter: &mut std::fmt::Formatter) -> std::fmt::Result {
        if self.details != "" {
            write!(formatter, "Sql query error {}, details {}.", self.sql_state, self.details)
        }
        else {
            write!(formatter, "Sql query error {}.", self.sql_state)
        }

    }
}

impl std::error::Error for Error {}

#[derive(Clone, Debug, PartialEq)]
pub enum SqlState {
    SuccessfulCompletion,
    Warning,
    WarningDynamicResultSetsReturned,
    WarningImplicitZeroBitPadding,
    WarningNullValueEliminatedInSetFunction,
    WarningPrivilegeNotGranted,
    WarningPrivilegeNotRevoked,
    WarningStringDataRightTruncation,
    WarningDeprecatedFeature,
    NoData,
    NoAdditionalDynamicResultSetsReturned,
    SqlStatementNotYetComplete,
    ConnectionException,
    ConnectionDoesNotExist,
    ConnectionFailure,
    SqlclientUnableToEstablishSqlconnection,
    SqlserverRejectedEstablishmentOfSqlconnection,
    TransactionResolutionUnknown,
    ProtocolViolation,
    TriggeredActionException,
    FeatureNotSupported,
    InvalidTransactionInitiation,
    LocatorException,
    InvalidLocatorSpecification,
    InvalidGrantor,
    InvalidGrantOperation,
    InvalidRoleSpecification,
    DiagnosticsException,
    StackedDiagnosticsAccessedWithoutActiveHandler,
    CaseNotFound,
    CardinalityViolation,
    DataException,
    ArraySubscriptError,
    CharacterNotInRepertoire,
    DatetimeFieldOverflow,
    DivisionByZero,
    ErrorInAssignment,
    EscapeCharacterConflict,
    IndicatorOverflow,
    IntervalFieldOverflow,
    InvalidArgumentForLogarithm,
    InvalidArgumentForNtileFunction,
    InvalidArgumentForNthValueFunction,
    InvalidArgumentForPowerFunction,
    InvalidArgumentForWidthBucketFunction,
    InvalidCharacterValueForCast,
    InvalidDatetimeFormat,
    InvalidEscapeCharacter,
    InvalidEscapeOctet,
    InvalidEscapeSequence,
    NonstandardUseOfEscapeCharacter,
    InvalidIndicatorParameterValue,
    InvalidParameterValue,
    InvalidPrecedingOrFollowingSize,
    InvalidRegularExpression,
    InvalidRowCountInLimitClause,
    InvalidRowCountInResultOffsetClause,
    InvalidTablesampleArgument,
    InvalidTablesampleRepeat,
    InvalidTimeZoneDisplacementValue,
    InvalidUseOfEscapeCharacter,
    MostSpecificTypeMismatch,
    NullValueNotAllowed,
    NullValueNoIndicatorParameter,
    NumericValueOutOfRange,
    SequenceGeneratorLimitExceeded,
    StringDataLengthMismatch,
    StringDataRightTruncation,
    SubstringError,
    TrimError,
    UnterminatedCString,
    ZeroLengthCharacterString,
    FloatingPointException,
    InvalidTextRepresentation,
    InvalidBinaryRepresentation,
    BadCopyFileFormat,
    UntranslatableCharacter,
    NotAnXmlDocument,
    InvalidXmlDocument,
    InvalidXmlContent,
    InvalidXmlComment,
    InvalidXmlProcessingInstruction,
    DuplicateJsonObjectKeyValue,
    InvalidArgumentForSqlJsonDatetimeFunction,
    InvalidJsonText,
    InvalidSqlJsonSubscript,
    MoreThanOneSqlJsonItem,
    NoSqlJsonItem,
    NonNumericSqlJsonItem,
    NonUniqueKeysInAJsonObject,
    SingletonSqlJsonItemRequired,
    SqlJsonArrayNotFound,
    SqlJsonMemberNotFound,
    SqlJsonNumberNotFound,
    SqlJsonObjectNotFound,
    TooManyJsonArrayElements,
    TooManyJsonObjectMembers,
    SqlJsonScalarRequired,
    IntegrityConstraintViolation,
    RestrictViolation,
    NotNullViolation,
    ForeignKeyViolation,
    UniqueViolation,
    CheckViolation,
    ExclusionViolation,
    InvalidCursorState,
    InvalidTransactionState,
    ActiveSqlTransaction,
    BranchTransactionAlreadyActive,
    HeldCursorRequiresSameIsolationLevel,
    InappropriateAccessModeForBranchTransaction,
    InappropriateIsolationLevelForBranchTransaction,
    NoActiveSqlTransactionForBranchTransaction,
    ReadOnlySqlTransaction,
    SchemaAndDataStatementMixingNotSupported,
    NoActiveSqlTransaction,
    InFailedSqlTransaction,
    IdleInTransactionSessionTimeout,
    InvalidSqlStatementName,
    TriggeredDataChangeViolation,
    InvalidAuthorizationSpecification,
    InvalidPassword,
    DependentPrivilegeDescriptorsStillExist,
    DependentObjectsStillExist,
    InvalidTransactionTermination,
    SqlRoutineException,
    FunctionExecutedNoReturnStatement,
    ModifyingSqlDataNotPermitted,
    ProhibitedSqlStatementAttempted,
    ReadingSqlDataNotPermitted,
    InvalidCursorName,
    ExternalRoutineException,
    ExternalRoutineContainingSqlNotPermitted,
    ExternalRoutineModifyingSqlDataNotPermitted,
    ExternalRoutineProhibitedSqlStatementAttempted,
    ExternalRoutineReadingSqlDataNotPermitted,
    ExternalRoutineInvocationException,
    ExternalRoutineInvocationInvalidSqlstateReturned,
    ExternalRoutineInvocationNullValueNotAllowed,
    ExternalRoutineInvocationTriggerProtocolViolated,
    ExternalRoutineInvocationSrfProtocolViolated,
    ExternalRoutineInvocationEventTriggerProtocolViolated,
    SavepointException,
    InvalidSavepointSpecification,
    InvalidCatalogName,
    InvalidSchemaName,
    TransactionRollback,
    TransactionIntegrityConstraintViolation,
    SerializationFailure,
    StatementCompletionUnknown,
    DeadlockDetected,
    SyntaxErrorOrAccessRuleViolation,
    SyntaxError,
    InsufficientPrivilege,
    CannotCoerce,
    GroupingError,
    WindowingError,
    InvalidRecursion,
    InvalidForeignKey,
    InvalidName,
    NameTooLong,
    ReservedName,
    DatatypeMismatch,
    IndeterminateDatatype,
    CollationMismatch,
    IndeterminateCollation,
    WrongObjectType,
    GeneratedAlways,
    UndefinedColumn,
    UndefinedFunction,
    UndefinedTable,
    UndefinedParameter,
    UndefinedObject,
    DuplicateColumn,
    DuplicateCursor,
    DuplicateDatabase,
    DuplicateFunction,
    DuplicatePreparedStatement,
    DuplicateSchema,
    DuplicateTable,
    DuplicateAlias,
    DuplicateObject,
    AmbiguousColumn,
    AmbiguousFunction,
    AmbiguousParameter,
    AmbiguousAlias,
    InvalidColumnReference,
    InvalidColumnDefinition,
    InvalidCursorDefinition,
    InvalidDatabaseDefinition,
    InvalidFunctionDefinition,
    InvalidPreparedStatementDefinition,
    InvalidSchemaDefinition,
    InvalidTableDefinition,
    InvalidObjectDefinition,
    WithCheckOptionViolation,
    InsufficientResources,
    DiskFull,
    OutOfMemory,
    TooManyConnections,
    ConfigurationLimitExceeded,
    ProgramLimitExceeded,
    StatementTooComplex,
    TooManyColumns,
    TooManyArguments,
    ObjectNotInPrerequisiteState,
    ObjectInUse,
    CantChangeRuntimeParam,
    LockNotAvailable,
    UnsafeNewEnumValueUsage,
    OperatorIntervention,
    QueryCanceled,
    AdminShutdown,
    CrashShutdown,
    CannotConnectNow,
    DatabaseDropped,
    SystemError,
    IoError,
    UndefinedFile,
    DuplicateFile,
    SnapshotTooOld,
    ConfigFileError,
    LockFileExists,
    FdwError,
    FdwColumnNameNotFound,
    FdwDynamicParameterValueNeeded,
    FdwFunctionSequenceError,
    FdwInconsistentDescriptorInformation,
    FdwInvalidAttributeValue,
    FdwInvalidColumnName,
    FdwInvalidColumnNumber,
    FdwInvalidDataType,
    FdwInvalidDataTypeDescriptors,
    FdwInvalidDescriptorFieldIdentifier,
    FdwInvalidHandle,
    FdwInvalidOptionIndex,
    FdwInvalidOptionName,
    FdwInvalidStringLengthOrBufferLength,
    FdwInvalidStringFormat,
    FdwInvalidUseOfNullPointer,
    FdwTooManyHandles,
    FdwOutOfMemory,
    FdwNoSchemas,
    FdwOptionNameNotFound,
    FdwReplyHandle,
    FdwSchemaNotFound,
    FdwTableNotFound,
    FdwUnableToCreateExecution,
    FdwUnableToCreateReply,
    FdwUnableToEstablishConnection,
    PlpgsqlError,
    RaiseException,
    NoDataFound,
    TooManyRows,
    AssertFailure,
    InternalError,
    DataCorrupted,
    IndexCorrupted,
    UnknownSqlState,
    DeserializeError,
    DeserializeErrorExpectedBoolean,
    DeserializeErrorExpectedInteger,
    DeserializeErrorExpectedString,
    DeserializeErrorUnexpectedNull,
    DeserializeErrorExpectedNull,
    DeserializeErrorExpectedArray,
    DeserializeErrorExpectedArrayComma,
    DeserializeErrorExpectedArrayEnd,
    DeserializeErrorExpectedMap,
    DeserializeErrorExpectedMapColon,
    DeserializeErrorExpectedMapComma,
    DeserializeErrorExpectedMapEnd,
    DeserializeErrorExpectedEnum,
    DeserializeErrorAnyNotSupported,
}

pub(crate) fn sql_state_from_code(code : &str) -> SqlState {
    return match code {
        "00000" => SqlState::SuccessfulCompletion,
        "01000" => SqlState::Warning,
        "0100C" => SqlState::WarningDynamicResultSetsReturned,
        "01008" => SqlState::WarningImplicitZeroBitPadding,
        "01003" => SqlState::WarningNullValueEliminatedInSetFunction,
        "01007" => SqlState::WarningPrivilegeNotGranted,
        "01006" => SqlState::WarningPrivilegeNotRevoked,
        "01004" => SqlState::WarningStringDataRightTruncation,
        "01P01" => SqlState::WarningDeprecatedFeature,
        "02000" => SqlState::NoData,
        "02001" => SqlState::NoAdditionalDynamicResultSetsReturned,
        "03000" => SqlState::SqlStatementNotYetComplete,
        "08000" => SqlState::ConnectionException,
        "08003" => SqlState::ConnectionDoesNotExist,
        "08006" => SqlState::ConnectionFailure,
        "08001" => SqlState::SqlclientUnableToEstablishSqlconnection,
        "08004" => SqlState::SqlserverRejectedEstablishmentOfSqlconnection,
        "08007" => SqlState::TransactionResolutionUnknown,
        "08P01" => SqlState::ProtocolViolation,
        "09000" => SqlState::TriggeredActionException,
        "0A000" => SqlState::FeatureNotSupported,
        "0B000" => SqlState::InvalidTransactionInitiation,
        "0F000" => SqlState::LocatorException,
        "0F001" => SqlState::InvalidLocatorSpecification,
        "0L000" => SqlState::InvalidGrantor,
        "0LP01" => SqlState::InvalidGrantOperation,
        "0P000" => SqlState::InvalidRoleSpecification,
        "0Z000" => SqlState::DiagnosticsException,
        "0Z002" => SqlState::StackedDiagnosticsAccessedWithoutActiveHandler,
        "20000" => SqlState::CaseNotFound,
        "21000" => SqlState::CardinalityViolation,
        "22000" => SqlState::DataException,
        "2202E" => SqlState::ArraySubscriptError,
        "22021" => SqlState::CharacterNotInRepertoire,
        "22008" => SqlState::DatetimeFieldOverflow,
        "22012" => SqlState::DivisionByZero,
        "22005" => SqlState::ErrorInAssignment,
        "2200B" => SqlState::EscapeCharacterConflict,
        "22022" => SqlState::IndicatorOverflow,
        "22015" => SqlState::IntervalFieldOverflow,
        "2201E" => SqlState::InvalidArgumentForLogarithm,
        "22014" => SqlState::InvalidArgumentForNtileFunction,
        "22016" => SqlState::InvalidArgumentForNthValueFunction,
        "2201F" => SqlState::InvalidArgumentForPowerFunction,
        "2201G" => SqlState::InvalidArgumentForWidthBucketFunction,
        "22018" => SqlState::InvalidCharacterValueForCast,
        "22007" => SqlState::InvalidDatetimeFormat,
        "22019" => SqlState::InvalidEscapeCharacter,
        "2200D" => SqlState::InvalidEscapeOctet,
        "22025" => SqlState::InvalidEscapeSequence,
        "22P06" => SqlState::NonstandardUseOfEscapeCharacter,
        "22010" => SqlState::InvalidIndicatorParameterValue,
        "22023" => SqlState::InvalidParameterValue,
        "22013" => SqlState::InvalidPrecedingOrFollowingSize,
        "2201B" => SqlState::InvalidRegularExpression,
        "2201W" => SqlState::InvalidRowCountInLimitClause,
        "2201X" => SqlState::InvalidRowCountInResultOffsetClause,
        "2202H" => SqlState::InvalidTablesampleArgument,
        "2202G" => SqlState::InvalidTablesampleRepeat,
        "22009" => SqlState::InvalidTimeZoneDisplacementValue,
        "2200C" => SqlState::InvalidUseOfEscapeCharacter,
        "2200G" => SqlState::MostSpecificTypeMismatch,
        "22004" => SqlState::NullValueNotAllowed,
        "22002" => SqlState::NullValueNoIndicatorParameter,
        "22003" => SqlState::NumericValueOutOfRange,
        "2200H" => SqlState::SequenceGeneratorLimitExceeded,
        "22026" => SqlState::StringDataLengthMismatch,
        "22001" => SqlState::StringDataRightTruncation,
        "22011" => SqlState::SubstringError,
        "22027" => SqlState::TrimError,
        "22024" => SqlState::UnterminatedCString,
        "2200F" => SqlState::ZeroLengthCharacterString,
        "22P01" => SqlState::FloatingPointException,
        "22P02" => SqlState::InvalidTextRepresentation,
        "22P03" => SqlState::InvalidBinaryRepresentation,
        "22P04" => SqlState::BadCopyFileFormat,
        "22P05" => SqlState::UntranslatableCharacter,
        "2200L" => SqlState::NotAnXmlDocument,
        "2200M" => SqlState::InvalidXmlDocument,
        "2200N" => SqlState::InvalidXmlContent,
        "2200S" => SqlState::InvalidXmlComment,
        "2200T" => SqlState::InvalidXmlProcessingInstruction,
        "22030" => SqlState::DuplicateJsonObjectKeyValue,
        "22031" => SqlState::InvalidArgumentForSqlJsonDatetimeFunction,
        "22032" => SqlState::InvalidJsonText,
        "22033" => SqlState::InvalidSqlJsonSubscript,
        "22034" => SqlState::MoreThanOneSqlJsonItem,
        "22035" => SqlState::NoSqlJsonItem,
        "22036" => SqlState::NonNumericSqlJsonItem,
        "22037" => SqlState::NonUniqueKeysInAJsonObject,
        "22038" => SqlState::SingletonSqlJsonItemRequired,
        "22039" => SqlState::SqlJsonArrayNotFound,
        "2203A" => SqlState::SqlJsonMemberNotFound,
        "2203B" => SqlState::SqlJsonNumberNotFound,
        "2203C" => SqlState::SqlJsonObjectNotFound,
        "2203D" => SqlState::TooManyJsonArrayElements,
        "2203E" => SqlState::TooManyJsonObjectMembers,
        "2203F" => SqlState::SqlJsonScalarRequired,
        "23000" => SqlState::IntegrityConstraintViolation,
        "23001" => SqlState::RestrictViolation,
        "23502" => SqlState::NotNullViolation,
        "23503" => SqlState::ForeignKeyViolation,
        "23505" => SqlState::UniqueViolation,
        "23514" => SqlState::CheckViolation,
        "23P01" => SqlState::ExclusionViolation,
        "24000" => SqlState::InvalidCursorState,
        "25000" => SqlState::InvalidTransactionState,
        "25001" => SqlState::ActiveSqlTransaction,
        "25002" => SqlState::BranchTransactionAlreadyActive,
        "25008" => SqlState::HeldCursorRequiresSameIsolationLevel,
        "25003" => SqlState::InappropriateAccessModeForBranchTransaction,
        "25004" => SqlState::InappropriateIsolationLevelForBranchTransaction,
        "25005" => SqlState::NoActiveSqlTransactionForBranchTransaction,
        "25006" => SqlState::ReadOnlySqlTransaction,
        "25007" => SqlState::SchemaAndDataStatementMixingNotSupported,
        "25P01" => SqlState::NoActiveSqlTransaction,
        "25P02" => SqlState::InFailedSqlTransaction,
        "25P03" => SqlState::IdleInTransactionSessionTimeout,
        "26000" => SqlState::InvalidSqlStatementName,
        "27000" => SqlState::TriggeredDataChangeViolation,
        "28000" => SqlState::InvalidAuthorizationSpecification,
        "28P01" => SqlState::InvalidPassword,
        "2B000" => SqlState::DependentPrivilegeDescriptorsStillExist,
        "2BP01" => SqlState::DependentObjectsStillExist,
        "2D000" => SqlState::InvalidTransactionTermination,
        "2F000" => SqlState::SqlRoutineException,
        "2F005" => SqlState::FunctionExecutedNoReturnStatement,
        "2F002" => SqlState::ModifyingSqlDataNotPermitted,
        "2F003" => SqlState::ProhibitedSqlStatementAttempted,
        "2F004" => SqlState::ReadingSqlDataNotPermitted,
        "34000" => SqlState::InvalidCursorName,
        "38000" => SqlState::ExternalRoutineException,
        "38001" => SqlState::ExternalRoutineContainingSqlNotPermitted,
        "38002" => SqlState::ExternalRoutineModifyingSqlDataNotPermitted,
        "38003" => SqlState::ExternalRoutineProhibitedSqlStatementAttempted,
        "38004" => SqlState::ExternalRoutineReadingSqlDataNotPermitted,
        "39000" => SqlState::ExternalRoutineInvocationException,
        "39001" => SqlState::ExternalRoutineInvocationInvalidSqlstateReturned,
        "39004" => SqlState::ExternalRoutineInvocationNullValueNotAllowed,
        "39P01" => SqlState::ExternalRoutineInvocationTriggerProtocolViolated,
        "39P02" => SqlState::ExternalRoutineInvocationSrfProtocolViolated,
        "39P03" => SqlState::ExternalRoutineInvocationEventTriggerProtocolViolated,
        "3B000" => SqlState::SavepointException,
        "3B001" => SqlState::InvalidSavepointSpecification,
        "3D000" => SqlState::InvalidCatalogName,
        "3F000" => SqlState::InvalidSchemaName,
        "40000" => SqlState::TransactionRollback,
        "40002" => SqlState::TransactionIntegrityConstraintViolation,
        "40001" => SqlState::SerializationFailure,
        "40003" => SqlState::StatementCompletionUnknown,
        "40P01" => SqlState::DeadlockDetected,
        "42000" => SqlState::SyntaxErrorOrAccessRuleViolation,
        "42601" => SqlState::SyntaxError,
        "42501" => SqlState::InsufficientPrivilege,
        "42846" => SqlState::CannotCoerce,
        "42803" => SqlState::GroupingError,
        "42P20" => SqlState::WindowingError,
        "42P19" => SqlState::InvalidRecursion,
        "42830" => SqlState::InvalidForeignKey,
        "42602" => SqlState::InvalidName,
        "42622" => SqlState::NameTooLong,
        "42939" => SqlState::ReservedName,
        "42804" => SqlState::DatatypeMismatch,
        "42P18" => SqlState::IndeterminateDatatype,
        "42P21" => SqlState::CollationMismatch,
        "42P22" => SqlState::IndeterminateCollation,
        "42809" => SqlState::WrongObjectType,
        "428C9" => SqlState::GeneratedAlways,
        "42703" => SqlState::UndefinedColumn,
        "42883" => SqlState::UndefinedFunction,
        "42P01" => SqlState::UndefinedTable,
        "42P02" => SqlState::UndefinedParameter,
        "42704" => SqlState::UndefinedObject,
        "42701" => SqlState::DuplicateColumn,
        "42P03" => SqlState::DuplicateCursor,
        "42P04" => SqlState::DuplicateDatabase,
        "42723" => SqlState::DuplicateFunction,
        "42P05" => SqlState::DuplicatePreparedStatement,
        "42P06" => SqlState::DuplicateSchema,
        "42P07" => SqlState::DuplicateTable,
        "42712" => SqlState::DuplicateAlias,
        "42710" => SqlState::DuplicateObject,
        "42702" => SqlState::AmbiguousColumn,
        "42725" => SqlState::AmbiguousFunction,
        "42P08" => SqlState::AmbiguousParameter,
        "42P09" => SqlState::AmbiguousAlias,
        "42P10" => SqlState::InvalidColumnReference,
        "42611" => SqlState::InvalidColumnDefinition,
        "42P11" => SqlState::InvalidCursorDefinition,
        "42P12" => SqlState::InvalidDatabaseDefinition,
        "42P13" => SqlState::InvalidFunctionDefinition,
        "42P14" => SqlState::InvalidPreparedStatementDefinition,
        "42P15" => SqlState::InvalidSchemaDefinition,
        "42P16" => SqlState::InvalidTableDefinition,
        "42P17" => SqlState::InvalidObjectDefinition,
        "44000" => SqlState::WithCheckOptionViolation,
        "53000" => SqlState::InsufficientResources,
        "53100" => SqlState::DiskFull,
        "53200" => SqlState::OutOfMemory,
        "53300" => SqlState::TooManyConnections,
        "53400" => SqlState::ConfigurationLimitExceeded,
        "54000" => SqlState::ProgramLimitExceeded,
        "54001" => SqlState::StatementTooComplex,
        "54011" => SqlState::TooManyColumns,
        "54023" => SqlState::TooManyArguments,
        "55000" => SqlState::ObjectNotInPrerequisiteState,
        "55006" => SqlState::ObjectInUse,
        "55P02" => SqlState::CantChangeRuntimeParam,
        "55P03" => SqlState::LockNotAvailable,
        "55P04" => SqlState::UnsafeNewEnumValueUsage,
        "57000" => SqlState::OperatorIntervention,
        "57014" => SqlState::QueryCanceled,
        "57P01" => SqlState::AdminShutdown,
        "57P02" => SqlState::CrashShutdown,
        "57P03" => SqlState::CannotConnectNow,
        "57P04" => SqlState::DatabaseDropped,
        "58000" => SqlState::SystemError,
        "58030" => SqlState::IoError,
        "58P01" => SqlState::UndefinedFile,
        "58P02" => SqlState::DuplicateFile,
        "72000" => SqlState::SnapshotTooOld,
        "F0000" => SqlState::ConfigFileError,
        "F0001" => SqlState::LockFileExists,
        "HV000" => SqlState::FdwError,
        "HV005" => SqlState::FdwColumnNameNotFound,
        "HV002" => SqlState::FdwDynamicParameterValueNeeded,
        "HV010" => SqlState::FdwFunctionSequenceError,
        "HV021" => SqlState::FdwInconsistentDescriptorInformation,
        "HV024" => SqlState::FdwInvalidAttributeValue,
        "HV007" => SqlState::FdwInvalidColumnName,
        "HV008" => SqlState::FdwInvalidColumnNumber,
        "HV004" => SqlState::FdwInvalidDataType,
        "HV006" => SqlState::FdwInvalidDataTypeDescriptors,
        "HV091" => SqlState::FdwInvalidDescriptorFieldIdentifier,
        "HV00B" => SqlState::FdwInvalidHandle,
        "HV00C" => SqlState::FdwInvalidOptionIndex,
        "HV00D" => SqlState::FdwInvalidOptionName,
        "HV090" => SqlState::FdwInvalidStringLengthOrBufferLength,
        "HV00A" => SqlState::FdwInvalidStringFormat,
        "HV009" => SqlState::FdwInvalidUseOfNullPointer,
        "HV014" => SqlState::FdwTooManyHandles,
        "HV001" => SqlState::FdwOutOfMemory,
        "HV00P" => SqlState::FdwNoSchemas,
        "HV00J" => SqlState::FdwOptionNameNotFound,
        "HV00K" => SqlState::FdwReplyHandle,
        "HV00Q" => SqlState::FdwSchemaNotFound,
        "HV00R" => SqlState::FdwTableNotFound,
        "HV00L" => SqlState::FdwUnableToCreateExecution,
        "HV00M" => SqlState::FdwUnableToCreateReply,
        "HV00N" => SqlState::FdwUnableToEstablishConnection,
        "P0000" => SqlState::PlpgsqlError,
        "P0001" => SqlState::RaiseException,
        "P0002" => SqlState::NoDataFound,
        "P0003" => SqlState::TooManyRows,
        "P0004" => SqlState::AssertFailure,
        "XX000" => SqlState::InternalError,
        "XX001" => SqlState::DataCorrupted,
        "XX002" => SqlState::IndexCorrupted,
        _ => SqlState::UnknownSqlState
    };
}

impl std::fmt::Display for SqlState {
    fn fmt(&self, formatter: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(formatter, "{:?}", self)
    }
}